server:
  port: 8080

manual-sql:
  url: jdbc:mysql://localhost:3306/lost_and_found?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
  username: root
  password: 123456
  driver: com.mysql.cj.jdbc.Driver

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lost_and_found?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 123456

  redis:
    host: localhost
    port: 6379
    database: 0

  mail:
    host: smtp.139.com
    port: 465
    username: 17805310458@139.com
    password: 2810713101QQqq
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
    protocol: smtps
    test-connection: true
    default-encoding: UTF-8

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.fake.demo.bean.entity
  configuration:
    map-underscore-to-camel-case: true

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  typeAliasesPackage: com.fake.demo.bean.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

