server:
  port: 8080

manual-sql:
  url: jdbc:mysql://localhost:3306/lost_and_found?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
  username: root
  password: 123456
  driver: com.mysql.cj.jdbc.Driver

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lost_and_found?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 123456

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.fake.demo.bean.entity
  configuration:
    map-underscore-to-camel-case: true